OldaleTown_OldCouple_MapScripts::
	.byte 0

OldaleTown_OldCouple_EventScript_Woman::
	msgbox OldaleTown_OldCouple_Text_HaveACookie, MSGBOX_NPC
	end

OldaleTown_OldCouple_EventScript_Man::
	msgbox OldaleTown_OldCouple_Text_TimeFlows, MSGBOX_NPC
	end

OldaleTown_OldCouple_Text_HaveACookie::
	.string "Life is too short to be stingy.\n"
	.string "I wish I learned that earlier.\p"
	.string "I hope you are always ready to give\n"
	.string "someone what they need.$"

OldaleTown_OldCouple_Text_TimeFlows::
	.string "I like spend all my time looking\n"
	.string "out on the bay.\p"
	.string "Time flows through everything and\n"
	.string "it does not appear that its slowing\l"
	.string "down any time soon.\p"
	.string "....\l"
	.string "At least the bay still provides\n"
	.string "me comfort.$"

